USE [master]
GO

/****** Object:  Database [Alternativa]    Script Date: 15/04/2021 19:06:03 ******/
CREATE DATABASE [Alternativa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Alternativa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Alternativa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Alternativa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Alternativa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Alternativa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Alternativa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Alternativa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Alternativa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Alternativa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Alternativa] SET ARITHABORT OFF 
GO

ALTER DATABASE [Alternativa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Alternativa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Alternativa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Alternativa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Alternativa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Alternativa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Alternativa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Alternativa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Alternativa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Alternativa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Alternativa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Alternativa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Alternativa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Alternativa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Alternativa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Alternativa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Alternativa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Alternativa] SET RECOVERY FULL 
GO

ALTER DATABASE [Alternativa] SET  MULTI_USER 
GO

ALTER DATABASE [Alternativa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Alternativa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Alternativa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Alternativa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Alternativa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Alternativa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Alternativa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Alternativa] SET  READ_WRITE 
GO

